import type { GetLandingWorkspaceData } from "@/shared/lib/generated-fdc";

export const DEFAULT_LANDING_WORKSPACE: GetLandingWorkspaceData = {
  landingHeroContents: [
    {
      id: "landing-hero-main",
      badgeText: "DATA CONNECT READY",
      titlePrefix: "Tái định nghĩa",
      titleAccent: "chẩn đoán",
      titleSuffix: "võng mạc bằng AI.",
      body: "Đồng bộ quy trình khám, AI, toa thuốc và báo cáo trong một nền tảng dữ liệu thống nhất cho bác sĩ và cơ sở y tế.",
      primaryButtonLabel: "Vào hệ thống",
      primaryButtonTarget: "/dashboard",
      secondaryButtonLabel: "Tìm hiểu thêm",
      secondaryButtonTarget: "#contact-section",
      patientCodeLabel: "ID: #PAT003",
      accuracyLabel: "98.4% chính xác",
      imagePath: "/doctor.png",
    },
  ],
  landingFeatures: [
    {
      id: "landing-feature-ai",
      section: "core-tech",
      iconKey: "activity",
      title: "Chẩn đoán AI",
      description: "Mô hình đọc đáy mắt và phân tầng nguy cơ theo từng bậc độ lâm sàng.",
      displayOrder: 1,
    },
    {
      id: "landing-feature-dashboard",
      section: "core-tech",
      iconKey: "dashboard",
      title: "Điều phối bác sĩ",
      description: "Tổng hợp lịch khám, hội chẩn, báo cáo và bệnh án trong cùng một giao diện.",
      displayOrder: 2,
    },
    {
      id: "landing-feature-shield",
      section: "core-tech",
      iconKey: "shield",
      title: "Dữ liệu an toàn",
      description: "Tập trung toàn bộ nội dung web vào Data Connect để dễ kiểm soát và mở rộng backend.",
      displayOrder: 3,
    },
    {
      id: "landing-feature-speed",
      section: "core-tech",
      iconKey: "zap",
      title: "Xử lý nhanh",
      description: "Từ tiếp nhận, số hóa hồ sơ đến toa thuốc và báo cáo đều có luồng dữ liệu thống nhất.",
      displayOrder: 4,
    },
  ],
  landingArticles: [
    {
      id: "landing-article-1",
      title: "Kiến thức đường huyết",
      excerpt: "Đường huyết cao có thể tổn thương mao mạch võng mạc nếu không tầm soát sớm.",
      content: "Tổng hợp nguy cơ và các mốc theo dõi sớm cho bệnh nhân tiểu đường.",
      link: "https://example.com/retina-1",
      imagePath: "/article1.png",
      iconKey: "stethoscope",
      displayOrder: 1,
    },
    {
      id: "landing-article-2",
      title: "Tầm soát mắt tại cơ sở",
      excerpt: "Mô hình tiếp cận AI giúp mở rộng năng lực tầm soát cho tuyến đầu.",
      content: "Cách điều phối khám, chụp ảnh và hội chẩn trong một luồng dữ liệu thống nhất.",
      link: "https://example.com/retina-2",
      imagePath: "/article2.png",
      iconKey: "eye",
      displayOrder: 2,
    },
    {
      id: "landing-article-3",
      title: "AI trong hỗ trợ quyết định",
      excerpt: "AI không thay thế bác sĩ, mà làm rõ ưu tiên và giảm thời gian đọc kết quả.",
      content: "Bác sĩ duyệt lại, ghi chú và lưu toàn bộ kết quả vào bệnh án trên Data Connect.",
      link: "https://example.com/retina-3",
      imagePath: "/article3.png",
      iconKey: "activity",
      displayOrder: 3,
    },
    {
      id: "landing-article-4",
      title: "Số hóa hồ sơ xét nghiệm",
      excerpt: "Biến biểu mẫu giấy thành dữ liệu có cấu trúc để tái sử dụng cho báo cáo và theo dõi.",
      content: "Từ OCR dữ liệu đến dashboard thống kê và toa thuốc mẫu hoàn toàn thống nhất.",
      link: "https://example.com/retina-4",
      imagePath: "/article4.png",
      iconKey: "file",
      displayOrder: 4,
    },
  ],
  supportContactInfos: [
    {
      id: "support-main",
      centerBadge: "TRUNG TÂM HỖ TRỢ",
      headlinePrefix: "Kết nối giải pháp",
      headlineAccent: "chẩn đoán",
      headlineBrand: "MedAssist",
      description: "Hợp nhất backend cho landing, dashboard và các quy trình nội bộ trên Data Connect.",
      email: "support@medassist.vn",
      phone: "+84 348 547 500",
      location: "TP. Hồ Chí Minh, Việt Nam",
    },
  ],
};
